// AUTO-GENERATED by scripts/gen_elements.js — do not hand-edit.
window.ELEMENTS = [
  {
    "z": 1,
    "sym": "H",
    "name": "Hydrogen",
    "period": 1,
    "group": 1,
    "category": "nonmetal",
    "origin": "bbn"
  },
  {
    "z": 2,
    "sym": "He",
    "name": "Helium",
    "period": 1,
    "group": 18,
    "category": "noble",
    "origin": "bbn"
  },
  {
    "z": 3,
    "sym": "Li",
    "name": "Lithium",
    "period": 2,
    "group": 1,
    "category": "alkali",
    "origin": "bbn"
  },
  {
    "z": 4,
    "sym": "Be",
    "name": "Beryllium",
    "period": 2,
    "group": 2,
    "category": "alkaline",
    "origin": "star"
  },
  {
    "z": 5,
    "sym": "B",
    "name": "Boron",
    "period": 2,
    "group": 13,
    "category": "metalloid",
    "origin": "star"
  },
  {
    "z": 6,
    "sym": "C",
    "name": "Carbon",
    "period": 2,
    "group": 14,
    "category": "nonmetal",
    "origin": "star"
  },
  {
    "z": 7,
    "sym": "N",
    "name": "Nitrogen",
    "period": 2,
    "group": 15,
    "category": "nonmetal",
    "origin": "star"
  },
  {
    "z": 8,
    "sym": "O",
    "name": "Oxygen",
    "period": 2,
    "group": 16,
    "category": "nonmetal",
    "origin": "star"
  },
  {
    "z": 9,
    "sym": "F",
    "name": "Fluorine",
    "period": 2,
    "group": 17,
    "category": "halogen",
    "origin": "star"
  },
  {
    "z": 10,
    "sym": "Ne",
    "name": "Neon",
    "period": 2,
    "group": 18,
    "category": "noble",
    "origin": "star"
  },
  {
    "z": 11,
    "sym": "Na",
    "name": "Sodium",
    "period": 3,
    "group": 1,
    "category": "alkali",
    "origin": "star"
  },
  {
    "z": 12,
    "sym": "Mg",
    "name": "Magnesium",
    "period": 3,
    "group": 2,
    "category": "alkaline",
    "origin": "star"
  },
  {
    "z": 13,
    "sym": "Al",
    "name": "Aluminium",
    "period": 3,
    "group": 13,
    "category": "posttransition",
    "origin": "star"
  },
  {
    "z": 14,
    "sym": "Si",
    "name": "Silicon",
    "period": 3,
    "group": 14,
    "category": "metalloid",
    "origin": "star"
  },
  {
    "z": 15,
    "sym": "P",
    "name": "Phosphorus",
    "period": 3,
    "group": 15,
    "category": "nonmetal",
    "origin": "star"
  },
  {
    "z": 16,
    "sym": "S",
    "name": "Sulfur",
    "period": 3,
    "group": 16,
    "category": "nonmetal",
    "origin": "star"
  },
  {
    "z": 17,
    "sym": "Cl",
    "name": "Chlorine",
    "period": 3,
    "group": 17,
    "category": "halogen",
    "origin": "star"
  },
  {
    "z": 18,
    "sym": "Ar",
    "name": "Argon",
    "period": 3,
    "group": 18,
    "category": "noble",
    "origin": "star"
  },
  {
    "z": 19,
    "sym": "K",
    "name": "Potassium",
    "period": 4,
    "group": 1,
    "category": "alkali",
    "origin": "star"
  },
  {
    "z": 20,
    "sym": "Ca",
    "name": "Calcium",
    "period": 4,
    "group": 2,
    "category": "alkaline",
    "origin": "star"
  },
  {
    "z": 21,
    "sym": "Sc",
    "name": "Scandium",
    "period": 4,
    "group": 3,
    "category": "transition",
    "origin": "star"
  },
  {
    "z": 22,
    "sym": "Ti",
    "name": "Titanium",
    "period": 4,
    "group": 4,
    "category": "transition",
    "origin": "star"
  },
  {
    "z": 23,
    "sym": "V",
    "name": "Vanadium",
    "period": 4,
    "group": 5,
    "category": "transition",
    "origin": "star"
  },
  {
    "z": 24,
    "sym": "Cr",
    "name": "Chromium",
    "period": 4,
    "group": 6,
    "category": "transition",
    "origin": "star"
  },
  {
    "z": 25,
    "sym": "Mn",
    "name": "Manganese",
    "period": 4,
    "group": 7,
    "category": "transition",
    "origin": "star"
  },
  {
    "z": 26,
    "sym": "Fe",
    "name": "Iron",
    "period": 4,
    "group": 8,
    "category": "transition",
    "origin": "star"
  },
  {
    "z": 27,
    "sym": "Co",
    "name": "Cobalt",
    "period": 4,
    "group": 9,
    "category": "transition",
    "origin": "massive"
  },
  {
    "z": 28,
    "sym": "Ni",
    "name": "Nickel",
    "period": 4,
    "group": 10,
    "category": "transition",
    "origin": "massive"
  },
  {
    "z": 29,
    "sym": "Cu",
    "name": "Copper",
    "period": 4,
    "group": 11,
    "category": "transition",
    "origin": "massive"
  },
  {
    "z": 30,
    "sym": "Zn",
    "name": "Zinc",
    "period": 4,
    "group": 12,
    "category": "transition",
    "origin": "massive"
  },
  {
    "z": 31,
    "sym": "Ga",
    "name": "Gallium",
    "period": 4,
    "group": 13,
    "category": "posttransition",
    "origin": "massive"
  },
  {
    "z": 32,
    "sym": "Ge",
    "name": "Germanium",
    "period": 4,
    "group": 14,
    "category": "metalloid",
    "origin": "massive"
  },
  {
    "z": 33,
    "sym": "As",
    "name": "Arsenic",
    "period": 4,
    "group": 15,
    "category": "metalloid",
    "origin": "massive"
  },
  {
    "z": 34,
    "sym": "Se",
    "name": "Selenium",
    "period": 4,
    "group": 16,
    "category": "nonmetal",
    "origin": "rprocess"
  },
  {
    "z": 35,
    "sym": "Br",
    "name": "Bromine",
    "period": 4,
    "group": 17,
    "category": "halogen",
    "origin": "rprocess"
  },
  {
    "z": 36,
    "sym": "Kr",
    "name": "Krypton",
    "period": 4,
    "group": 18,
    "category": "noble",
    "origin": "rprocess"
  },
  {
    "z": 37,
    "sym": "Rb",
    "name": "Rubidium",
    "period": 5,
    "group": 1,
    "category": "alkali",
    "origin": "rprocess"
  },
  {
    "z": 38,
    "sym": "Sr",
    "name": "Strontium",
    "period": 5,
    "group": 2,
    "category": "alkaline",
    "origin": "rprocess"
  },
  {
    "z": 39,
    "sym": "Y",
    "name": "Yttrium",
    "period": 5,
    "group": 3,
    "category": "transition",
    "origin": "rprocess"
  },
  {
    "z": 40,
    "sym": "Zr",
    "name": "Zirconium",
    "period": 5,
    "group": 4,
    "category": "transition",
    "origin": "rprocess"
  },
  {
    "z": 41,
    "sym": "Nb",
    "name": "Niobium",
    "period": 5,
    "group": 5,
    "category": "transition",
    "origin": "rprocess"
  },
  {
    "z": 42,
    "sym": "Mo",
    "name": "Molybdenum",
    "period": 5,
    "group": 6,
    "category": "transition",
    "origin": "rprocess"
  },
  {
    "z": 43,
    "sym": "Tc",
    "name": "Technetium",
    "period": 5,
    "group": 7,
    "category": "transition",
    "origin": "rprocess"
  },
  {
    "z": 44,
    "sym": "Ru",
    "name": "Ruthenium",
    "period": 5,
    "group": 8,
    "category": "transition",
    "origin": "rprocess"
  },
  {
    "z": 45,
    "sym": "Rh",
    "name": "Rhodium",
    "period": 5,
    "group": 9,
    "category": "transition",
    "origin": "rprocess"
  },
  {
    "z": 46,
    "sym": "Pd",
    "name": "Palladium",
    "period": 5,
    "group": 10,
    "category": "transition",
    "origin": "rprocess"
  },
  {
    "z": 47,
    "sym": "Ag",
    "name": "Silver",
    "period": 5,
    "group": 11,
    "category": "transition",
    "origin": "rprocess"
  },
  {
    "z": 48,
    "sym": "Cd",
    "name": "Cadmium",
    "period": 5,
    "group": 12,
    "category": "transition",
    "origin": "rprocess"
  },
  {
    "z": 49,
    "sym": "In",
    "name": "Indium",
    "period": 5,
    "group": 13,
    "category": "posttransition",
    "origin": "rprocess"
  },
  {
    "z": 50,
    "sym": "Sn",
    "name": "Tin",
    "period": 5,
    "group": 14,
    "category": "posttransition",
    "origin": "rprocess"
  },
  {
    "z": 51,
    "sym": "Sb",
    "name": "Antimony",
    "period": 5,
    "group": 15,
    "category": "metalloid",
    "origin": "rprocess"
  },
  {
    "z": 52,
    "sym": "Te",
    "name": "Tellurium",
    "period": 5,
    "group": 16,
    "category": "metalloid",
    "origin": "rprocess"
  },
  {
    "z": 53,
    "sym": "I",
    "name": "Iodine",
    "period": 5,
    "group": 17,
    "category": "halogen",
    "origin": "rprocess"
  },
  {
    "z": 54,
    "sym": "Xe",
    "name": "Xenon",
    "period": 5,
    "group": 18,
    "category": "noble",
    "origin": "rprocess"
  },
  {
    "z": 55,
    "sym": "Cs",
    "name": "Caesium",
    "period": 6,
    "group": 1,
    "category": "alkali",
    "origin": "rprocess"
  },
  {
    "z": 56,
    "sym": "Ba",
    "name": "Barium",
    "period": 6,
    "group": 2,
    "category": "alkaline",
    "origin": "rprocess"
  },
  {
    "z": 57,
    "sym": "La",
    "name": "Lanthanum",
    "period": 8,
    "group": 3,
    "category": "lanthanide",
    "origin": "rprocess"
  },
  {
    "z": 58,
    "sym": "Ce",
    "name": "Cerium",
    "period": 8,
    "group": 4,
    "category": "lanthanide",
    "origin": "rprocess"
  },
  {
    "z": 59,
    "sym": "Pr",
    "name": "Praseodymium",
    "period": 8,
    "group": 5,
    "category": "lanthanide",
    "origin": "rprocess"
  },
  {
    "z": 60,
    "sym": "Nd",
    "name": "Neodymium",
    "period": 8,
    "group": 6,
    "category": "lanthanide",
    "origin": "rprocess"
  },
  {
    "z": 61,
    "sym": "Pm",
    "name": "Promethium",
    "period": 8,
    "group": 7,
    "category": "lanthanide",
    "origin": "rprocess"
  },
  {
    "z": 62,
    "sym": "Sm",
    "name": "Samarium",
    "period": 8,
    "group": 8,
    "category": "lanthanide",
    "origin": "rprocess"
  },
  {
    "z": 63,
    "sym": "Eu",
    "name": "Europium",
    "period": 8,
    "group": 9,
    "category": "lanthanide",
    "origin": "rprocess"
  },
  {
    "z": 64,
    "sym": "Gd",
    "name": "Gadolinium",
    "period": 8,
    "group": 10,
    "category": "lanthanide",
    "origin": "rprocess"
  },
  {
    "z": 65,
    "sym": "Tb",
    "name": "Terbium",
    "period": 8,
    "group": 11,
    "category": "lanthanide",
    "origin": "rprocess"
  },
  {
    "z": 66,
    "sym": "Dy",
    "name": "Dysprosium",
    "period": 8,
    "group": 12,
    "category": "lanthanide",
    "origin": "rprocess"
  },
  {
    "z": 67,
    "sym": "Ho",
    "name": "Holmium",
    "period": 8,
    "group": 13,
    "category": "lanthanide",
    "origin": "rprocess"
  },
  {
    "z": 68,
    "sym": "Er",
    "name": "Erbium",
    "period": 8,
    "group": 14,
    "category": "lanthanide",
    "origin": "rprocess"
  },
  {
    "z": 69,
    "sym": "Tm",
    "name": "Thulium",
    "period": 8,
    "group": 15,
    "category": "lanthanide",
    "origin": "rprocess"
  },
  {
    "z": 70,
    "sym": "Yb",
    "name": "Ytterbium",
    "period": 8,
    "group": 16,
    "category": "lanthanide",
    "origin": "rprocess"
  },
  {
    "z": 71,
    "sym": "Lu",
    "name": "Lutetium",
    "period": 8,
    "group": 17,
    "category": "lanthanide",
    "origin": "rprocess"
  },
  {
    "z": 72,
    "sym": "Hf",
    "name": "Hafnium",
    "period": 6,
    "group": 4,
    "category": "transition",
    "origin": "rprocess"
  },
  {
    "z": 73,
    "sym": "Ta",
    "name": "Tantalum",
    "period": 6,
    "group": 5,
    "category": "transition",
    "origin": "rprocess"
  },
  {
    "z": 74,
    "sym": "W",
    "name": "Tungsten",
    "period": 6,
    "group": 6,
    "category": "transition",
    "origin": "rprocess"
  },
  {
    "z": 75,
    "sym": "Re",
    "name": "Rhenium",
    "period": 6,
    "group": 7,
    "category": "transition",
    "origin": "rprocess"
  },
  {
    "z": 76,
    "sym": "Os",
    "name": "Osmium",
    "period": 6,
    "group": 8,
    "category": "transition",
    "origin": "rprocess"
  },
  {
    "z": 77,
    "sym": "Ir",
    "name": "Iridium",
    "period": 6,
    "group": 9,
    "category": "transition",
    "origin": "rprocess"
  },
  {
    "z": 78,
    "sym": "Pt",
    "name": "Platinum",
    "period": 6,
    "group": 10,
    "category": "transition",
    "origin": "rprocess"
  },
  {
    "z": 79,
    "sym": "Au",
    "name": "Gold",
    "period": 6,
    "group": 11,
    "category": "transition",
    "origin": "rprocess"
  },
  {
    "z": 80,
    "sym": "Hg",
    "name": "Mercury",
    "period": 6,
    "group": 12,
    "category": "transition",
    "origin": "rprocess"
  },
  {
    "z": 81,
    "sym": "Tl",
    "name": "Thallium",
    "period": 6,
    "group": 13,
    "category": "posttransition",
    "origin": "rprocess"
  },
  {
    "z": 82,
    "sym": "Pb",
    "name": "Lead",
    "period": 6,
    "group": 14,
    "category": "posttransition",
    "origin": "rprocess"
  },
  {
    "z": 83,
    "sym": "Bi",
    "name": "Bismuth",
    "period": 6,
    "group": 15,
    "category": "posttransition",
    "origin": "rprocess"
  },
  {
    "z": 84,
    "sym": "Po",
    "name": "Polonium",
    "period": 6,
    "group": 16,
    "category": "posttransition",
    "origin": "rprocess"
  },
  {
    "z": 85,
    "sym": "At",
    "name": "Astatine",
    "period": 6,
    "group": 17,
    "category": "halogen",
    "origin": "rprocess"
  },
  {
    "z": 86,
    "sym": "Rn",
    "name": "Radon",
    "period": 6,
    "group": 18,
    "category": "noble",
    "origin": "rprocess"
  },
  {
    "z": 87,
    "sym": "Fr",
    "name": "Francium",
    "period": 7,
    "group": 1,
    "category": "alkali",
    "origin": "rprocess"
  },
  {
    "z": 88,
    "sym": "Ra",
    "name": "Radium",
    "period": 7,
    "group": 2,
    "category": "alkaline",
    "origin": "rprocess"
  },
  {
    "z": 89,
    "sym": "Ac",
    "name": "Actinium",
    "period": 9,
    "group": 3,
    "category": "actinide",
    "origin": "rprocess"
  },
  {
    "z": 90,
    "sym": "Th",
    "name": "Thorium",
    "period": 9,
    "group": 4,
    "category": "actinide",
    "origin": "rprocess"
  },
  {
    "z": 91,
    "sym": "Pa",
    "name": "Protactinium",
    "period": 9,
    "group": 5,
    "category": "actinide",
    "origin": "rprocess"
  },
  {
    "z": 92,
    "sym": "U",
    "name": "Uranium",
    "period": 9,
    "group": 6,
    "category": "actinide",
    "origin": "rprocess"
  },
  {
    "z": 93,
    "sym": "Np",
    "name": "Neptunium",
    "period": 9,
    "group": 7,
    "category": "actinide",
    "origin": "synthetic"
  },
  {
    "z": 94,
    "sym": "Pu",
    "name": "Plutonium",
    "period": 9,
    "group": 8,
    "category": "actinide",
    "origin": "synthetic"
  },
  {
    "z": 95,
    "sym": "Am",
    "name": "Americium",
    "period": 9,
    "group": 9,
    "category": "actinide",
    "origin": "synthetic"
  },
  {
    "z": 96,
    "sym": "Cm",
    "name": "Curium",
    "period": 9,
    "group": 10,
    "category": "actinide",
    "origin": "synthetic"
  },
  {
    "z": 97,
    "sym": "Bk",
    "name": "Berkelium",
    "period": 9,
    "group": 11,
    "category": "actinide",
    "origin": "synthetic"
  },
  {
    "z": 98,
    "sym": "Cf",
    "name": "Californium",
    "period": 9,
    "group": 12,
    "category": "actinide",
    "origin": "synthetic"
  },
  {
    "z": 99,
    "sym": "Es",
    "name": "Einsteinium",
    "period": 9,
    "group": 13,
    "category": "actinide",
    "origin": "synthetic"
  },
  {
    "z": 100,
    "sym": "Fm",
    "name": "Fermium",
    "period": 9,
    "group": 14,
    "category": "actinide",
    "origin": "synthetic"
  },
  {
    "z": 101,
    "sym": "Md",
    "name": "Mendelevium",
    "period": 9,
    "group": 15,
    "category": "actinide",
    "origin": "synthetic"
  },
  {
    "z": 102,
    "sym": "No",
    "name": "Nobelium",
    "period": 9,
    "group": 16,
    "category": "actinide",
    "origin": "synthetic"
  },
  {
    "z": 103,
    "sym": "Lr",
    "name": "Lawrencium",
    "period": 9,
    "group": 17,
    "category": "actinide",
    "origin": "synthetic"
  },
  {
    "z": 104,
    "sym": "Rf",
    "name": "Rutherfordium",
    "period": 7,
    "group": 4,
    "category": "transition",
    "origin": "synthetic"
  },
  {
    "z": 105,
    "sym": "Db",
    "name": "Dubnium",
    "period": 7,
    "group": 5,
    "category": "transition",
    "origin": "synthetic"
  },
  {
    "z": 106,
    "sym": "Sg",
    "name": "Seaborgium",
    "period": 7,
    "group": 6,
    "category": "transition",
    "origin": "synthetic"
  },
  {
    "z": 107,
    "sym": "Bh",
    "name": "Bohrium",
    "period": 7,
    "group": 7,
    "category": "transition",
    "origin": "synthetic"
  },
  {
    "z": 108,
    "sym": "Hs",
    "name": "Hassium",
    "period": 7,
    "group": 8,
    "category": "transition",
    "origin": "synthetic"
  },
  {
    "z": 109,
    "sym": "Mt",
    "name": "Meitnerium",
    "period": 7,
    "group": 9,
    "category": "transition",
    "origin": "synthetic"
  },
  {
    "z": 110,
    "sym": "Ds",
    "name": "Darmstadtium",
    "period": 7,
    "group": 10,
    "category": "transition",
    "origin": "synthetic"
  },
  {
    "z": 111,
    "sym": "Rg",
    "name": "Roentgenium",
    "period": 7,
    "group": 11,
    "category": "transition",
    "origin": "synthetic"
  },
  {
    "z": 112,
    "sym": "Cn",
    "name": "Copernicium",
    "period": 7,
    "group": 12,
    "category": "transition",
    "origin": "synthetic"
  },
  {
    "z": 113,
    "sym": "Nh",
    "name": "Nihonium",
    "period": 7,
    "group": 13,
    "category": "posttransition",
    "origin": "synthetic"
  },
  {
    "z": 114,
    "sym": "Fl",
    "name": "Flerovium",
    "period": 7,
    "group": 14,
    "category": "posttransition",
    "origin": "synthetic"
  },
  {
    "z": 115,
    "sym": "Mc",
    "name": "Moscovium",
    "period": 7,
    "group": 15,
    "category": "posttransition",
    "origin": "synthetic"
  },
  {
    "z": 116,
    "sym": "Lv",
    "name": "Livermorium",
    "period": 7,
    "group": 16,
    "category": "posttransition",
    "origin": "synthetic"
  },
  {
    "z": 117,
    "sym": "Ts",
    "name": "Tennessine",
    "period": 7,
    "group": 17,
    "category": "halogen",
    "origin": "synthetic"
  },
  {
    "z": 118,
    "sym": "Og",
    "name": "Oganesson",
    "period": 7,
    "group": 18,
    "category": "noble",
    "origin": "synthetic"
  }
];
